services:
  routing-engine:
    build:
      context: ./graph_server/routing-engine
    networks:
      - rescuemind-net

  graph-api:
    build:
      context: ./graph_server/rescuemind-api
    environment:
      - GRPC_SERVER_URL=routing-engine:50051
    depends_on:
      - routing-engine
    networks:
      - rescuemind-net

  rag-server:
    build:
      context: ./RAG_Server
    networks:
      - rescuemind-net

  gateway:
    build:
      context: ./main_server
    environment:
      - PORT=6000
    networks:
      - rescuemind-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gateway
      - rag-server
      - graph-api
    networks:
      - rescuemind-net

networks:
  rescuemind-net:
    driver: bridge
