# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'routing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrouting.proto\x12\x07routing\"*\n\x0cRouteRequest\x12\r\n\x05start\x18\x01 \x01(\t\x12\x0b\n\x03\x65nd\x18\x02 \x01(\t\"S\n\x05Route\x12\x0c\n\x04path\x18\x01 \x03(\t\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\x12\x16\n\x0e\x65stimated_time\x18\x03 \x01(\x02\x12\x12\n\nroute_type\x18\x04 \x01(\t\"/\n\rRouteResponse\x12\x1e\n\x06routes\x18\x01 \x03(\x0b\x32\x0e.routing.Route2O\n\x0eRoutingService\x12=\n\x0c\x43omputeRoute\x12\x15.routing.RouteRequest\x1a\x16.routing.RouteResponseB\'Z%rescuemind-api/internal/routing/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%rescuemind-api/internal/routing/proto'
  _globals['_ROUTEREQUEST']._serialized_start=26
  _globals['_ROUTEREQUEST']._serialized_end=68
  _globals['_ROUTE']._serialized_start=70
  _globals['_ROUTE']._serialized_end=153
  _globals['_ROUTERESPONSE']._serialized_start=155
  _globals['_ROUTERESPONSE']._serialized_end=202
  _globals['_ROUTINGSERVICE']._serialized_start=204
  _globals['_ROUTINGSERVICE']._serialized_end=283
# @@protoc_insertion_point(module_scope)
