// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: rescuemind-api/proto/routing.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_rescuemind_api_proto_routing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rescuemind_api_proto_routing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_rescuemind_api_proto_routing_proto_rawDescGZIP(), []int{0}
}

func (x *RouteRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *RouteRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []string               `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	Distance      float32                `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	EstimatedTime float32                `protobuf:"fixed32,3,opt,name=estimated_time,json=estimatedTime,proto3" json:"estimated_time,omitempty"`
	RouteType     string                 `protobuf:"bytes,4,opt,name=route_type,json=routeType,proto3" json:"route_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_rescuemind_api_proto_routing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_rescuemind_api_proto_routing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_rescuemind_api_proto_routing_proto_rawDescGZIP(), []int{1}
}

func (x *Route) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *Route) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Route) GetEstimatedTime() float32 {
	if x != nil {
		return x.EstimatedTime
	}
	return 0
}

func (x *Route) GetRouteType() string {
	if x != nil {
		return x.RouteType
	}
	return ""
}

type RouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*Route               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_rescuemind_api_proto_routing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rescuemind_api_proto_routing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_rescuemind_api_proto_routing_proto_rawDescGZIP(), []int{2}
}

func (x *RouteResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

var File_rescuemind_api_proto_routing_proto protoreflect.FileDescriptor

const file_rescuemind_api_proto_routing_proto_rawDesc = "" +
	"\n" +
	"\"rescuemind-api/proto/routing.proto\x12\arouting\"6\n" +
	"\fRouteRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\"}\n" +
	"\x05Route\x12\x12\n" +
	"\x04path\x18\x01 \x03(\tR\x04path\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\x12%\n" +
	"\x0eestimated_time\x18\x03 \x01(\x02R\restimatedTime\x12\x1d\n" +
	"\n" +
	"route_type\x18\x04 \x01(\tR\trouteType\"7\n" +
	"\rRouteResponse\x12&\n" +
	"\x06routes\x18\x01 \x03(\v2\x0e.routing.RouteR\x06routes2O\n" +
	"\x0eRoutingService\x12=\n" +
	"\fComputeRoute\x12\x15.routing.RouteRequest\x1a\x16.routing.RouteResponseB'Z%rescuemind-api/internal/routing/protob\x06proto3"

var (
	file_rescuemind_api_proto_routing_proto_rawDescOnce sync.Once
	file_rescuemind_api_proto_routing_proto_rawDescData []byte
)

func file_rescuemind_api_proto_routing_proto_rawDescGZIP() []byte {
	file_rescuemind_api_proto_routing_proto_rawDescOnce.Do(func() {
		file_rescuemind_api_proto_routing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rescuemind_api_proto_routing_proto_rawDesc), len(file_rescuemind_api_proto_routing_proto_rawDesc)))
	})
	return file_rescuemind_api_proto_routing_proto_rawDescData
}

var file_rescuemind_api_proto_routing_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rescuemind_api_proto_routing_proto_goTypes = []any{
	(*RouteRequest)(nil),  // 0: routing.RouteRequest
	(*Route)(nil),         // 1: routing.Route
	(*RouteResponse)(nil), // 2: routing.RouteResponse
}
var file_rescuemind_api_proto_routing_proto_depIdxs = []int32{
	1, // 0: routing.RouteResponse.routes:type_name -> routing.Route
	0, // 1: routing.RoutingService.ComputeRoute:input_type -> routing.RouteRequest
	2, // 2: routing.RoutingService.ComputeRoute:output_type -> routing.RouteResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rescuemind_api_proto_routing_proto_init() }
func file_rescuemind_api_proto_routing_proto_init() {
	if File_rescuemind_api_proto_routing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rescuemind_api_proto_routing_proto_rawDesc), len(file_rescuemind_api_proto_routing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rescuemind_api_proto_routing_proto_goTypes,
		DependencyIndexes: file_rescuemind_api_proto_routing_proto_depIdxs,
		MessageInfos:      file_rescuemind_api_proto_routing_proto_msgTypes,
	}.Build()
	File_rescuemind_api_proto_routing_proto = out.File
	file_rescuemind_api_proto_routing_proto_goTypes = nil
	file_rescuemind_api_proto_routing_proto_depIdxs = nil
}
